### ISSUE TITLE
How to run encrypted DNS Server as a Service?

### ISSUE THREAD

**Issue by Gill-Bates** [jedisct1/encrypted-dns-server#15]
How can I run the Application as as service when I boot up the Machine?

**Comment by jedisct1** [comment]
Is it on Linux?

If this is the case, and unless you are using a different system to run services, most Linux distributions use `systemd` to run services.

But I'm not very familiar with systemd, so Google [may be way more useful](https://www.google.com/search?q=how+to+write+a+systemd+service&oq=how+to+write+a+systemd+service).

**Comment by Gill-Bates** [comment]
Solved! Thank you!

`nano /etc/systemd/system/encrypted-dns.service`

```
[Unit]
Description=Encrypted DNS Server
After=network.target
StartLimitIntervalSec=0
[Service]
Type=Simple
Restart=always
RestartSec=1
WorkingDirectory=/bin/
ExecStart=/bin/bash encrypted-dns

[Install]
WantedBy=multi-user.target
```

Finally...

```
systemctl start encrypted-dns.service
systemctl enable encrypted-dns.service
```

**Comment by jedisct1** [comment]
Thank you!
