### ISSUE TITLE
It it possible to disable cache so that all requests are always forwarded to upstream servers?

### ISSUE THREAD

**Issue by lolcocks123** [jedisct1/encrypted-dns-server#19]
Hello,

Currently running an encrypted-dns-server directly as suggested here: https://github.com/jedisct1/dnscrypt-server-docker/issues/37
Works flawlessly, thank you jedisct1.

I use an upstream server of OpenDNS.

My question is, is there a way to disable caching so that all requests are forwarded to OpenDNS?

Adding `cache=false` to the config file did not work for me and settings cache size to 0 is not allowed, a minimum of 3 is required.

Is it possible to disable caching?

**Comment by jedisct1** [comment]
You can set

```toml
cache_ttl_min = 0
cache_ttl_max = 0
```
