### ISSUE TITLE
Create a container with the new server

### ISSUE THREAD

**Issue by lucenera** [jedisct1/encrypted-dns-server#2]
Hi Frank,
I read about your new project. I would like to be able to convert the two servers that I keep to the new encrypted-dns-server.. For now, I use the container you published on Docker Hub, which uses dnscrypt-wrapper. Not having technical knowledge on DNS servers, I ask you if you can create a container that replaces dnscrypt-wrapper with encrypted-dns-server.
Thanks and good job.

**Comment by jedisct1** [comment]
Working on it! :smile

**Comment by jedisct1** [comment]
This is happening in that branch: https://github.com/jedisct1/dnscrypt-server-docker/tree/new-server

**Comment by lucenera** [comment]
Thanks Frank.  Never let me down!

**Comment by jedisct1** [comment]
Hi @lucenera ,

An updated image is now available!

And the standard upgrade procedure should work with it. But instead of using `jedisct1/dnscrypt-server:latest`, you have to use `jedisct1/dnscrypt-server:beta`.

**Comment by lucenera** [comment]
Thank you so much. Now I try it.

**Comment by lucenera** [comment]
It works. But I have two doubts:
1) because this difference in size between latest and beta;
2) what does this error mean in the log? (/opt/unbound/sbin/unbound-control-setup fatal error: could not create unbound_control.pem)
![Schermata del 2019-09-25 00-19-15](https://user-images.githubusercontent.com/35407790/65554539-2db57d00-df2a-11e9-93f9-b6f6d3737c32.png)
[docker-log.txt](https://github.com/jedisct1/encrypted-dns-server/files/3649705/docker-log.txt)

**Comment by jedisct1** [comment]
Thanks for giving it a spin!

Did you actually install the beta? The docker log you posted seem to come form the previous version.

The difference in size was mainly due to the Rust compiler not being removed. This should be fixed now.

**Comment by lucenera** [comment]
I'm on the new version (beta tag).  The size corresponds to the pull.  Tell me if there is another way to verify.
