### ISSUE TITLE
DNS requests being leaked even after setting up an DNSCrypt server.

### ISSUE THREAD

**Issue by lolcocks123** [jedisct1/encrypted-dns-server#20]
Hello,

So I managed to get my DNSCrypt server up and running and it forwards all the requests to OpenDNS. Works great with my broadband connection. Thank you @jedisct1.

If I do not use DNSCrypt and used any simple DNS service, my mobile's ISP (Vodafone) would leak all the DNS requests.

However, even after setting up a DNSCrypt server and using my mobile's internet via hotspot, all DNS requests are being leaked. Same issue does not occur when using my Broadband Connection over the same WiFi adapter.

I have disabled fall back DNS servers on the client side. I have set the DNS to use on both wired and wireless adapter to 127.0.0.1, (although both were tested over WiFi).

I don't get what I am doing wrong. How is my mobile's ISP (Vodafone) is able to leak DNS entries sent over DNSCrypt?

EDIT:
The server is being hosted on a DigitalOcean VPS.

**Comment by jedisct1** [comment]
On your phone (iOS? Android?), when using 3G/4G instead of WiFi, DNS queries go to your carrier’s DNS server instead of the DNS server you configured (how?).

Is that the issue you are describing?

**Comment by lolcocks123** [comment]
> 
> 
> On your phone (iOS? Android?), when using 3G/4G instead of WiFi, DNS queries go to your carrier’s DNS server instead of the DNS server you configured (how?).
> 
> Is that the issue you are describing?


~~Ummmm, no~~

~~Let me simplify. I have~~

~~- 1 Laptop~~
~~- 1 Broadband Connection (YOU Broadband)~~
~~- 1 Android phone (with Vodafone SIM card in it).~~

~~When I connect my laptop to my Broadband connection over WiFi, all the DNS Requests go through my laptop's dnscrypt-proxy to my encrypted-dns-server. Everything works well here.~~

~~When I turn on hotspot on my phone and connect my laptop to that hotspot, Vodafone leaks my DNS.~~
~~It's the same laptop, but DNS requests no longer go through DNSCrypt.~~



Whilst typing this message, I realised my mistake. When I connected my laptop to my phone's hotspot, IPv6 was enabled, so the DHCP network settings my laptop received were IPv6, which included using my ISP's DNS.

Thank you for all your help @jedisct1, all my issues are resolved now.
