### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by Icekiss69** [jedisct1/encrypted-dns-server#21]
Hiya
is there a windows version? and a tutorial? I have windows not linux

**Comment by jedisct1** [comment]
I don't think it currently works on Windows.

It should be pretty simple to make it work (I think the only incompatibilities are privileges drop and the shared UDP socket), but I don't have a Windows machine.

If someone (you?) wants to contribute the missing bits to make it work on Windows, that would be great!

**Comment by Icekiss69** [comment]
I am not a programmer
there is a free 6 month trial here for windows
https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2016

**Comment by jedisct1** [comment]
Sorry, I have a Mac.
