### ISSUE TITLE
How to use DNS final relay

### ISSUE THREAD

**Issue by thb007** [jedisct1/encrypted-dns-server#22]
The last line of this page states that DNS relay is supported, but I do n’t know how to use this thing. I ’m a novice, I ca n’t use it. Can you give me a tutorial?

**Comment by jedisct1** [comment]
In order to enable relaying, simple change

```toml
enabled = false
```

to

```toml
enabled = true
```

in the `[anonymized_dns]` section.

The DNS relay stamp will then be printed when the server starts:

```txt
[INFO ] State file [encrypted-dns.state] found; using existing provider key
...
[INFO ] DNS Stamp for Anonymized DNS relaying: sdns://gQ0xMjcuMC4wLjE6NDQz
```

**Comment by thb007** [comment]
Can this value be written casually? The default is provider_name = "secure.dns.test"

**Comment by jedisct1** [comment]
In `dnscrypt-proxy`, the stamp can be used directly, but you can also use the relay name, if it is present in one of the loaded lists, or defined in the `[static]` section of the configuration file.

See the documentation on using anonymized DNS here: https://github.com/dnscrypt/dnscrypt-proxy/wiki/Anonymized-DNS
