### ISSUE TITLE
Number of client queries received type

### ISSUE THREAD

**Issue by pengelana** [jedisct1/encrypted-dns-server#23]
~~~
# HELP encrypted_dns_client_queries Number of client queries received
# TYPE encrypted_dns_client_queries gauge
~~~

client_queries (gauge) = client_queries_udp (counter) +  client_queries_tcp (counter)

The total client queries type should be `counter`.

Merry Christmas!

**Comment by jedisct1** [comment]
Hi!

Does it make a difference?

The client queries is a computed value, by adding both counters. Counters can only be incremented.

**Comment by pengelana** [comment]
I’m using munin to plot a graph, if I define as gauge the graph will show wrong value.

It’s should be fine by manually change the type to counter.

**Comment by jedisct1** [comment]
Unfortunately, the Prometheus client library doesn't support setting counters :(

**Comment by pengelana** [comment]
It’s fixed, change the type manually with munin plugin.

Thanks!
