### ISSUE TITLE
How to load balance

### ISSUE THREAD

**Issue by eterry1388** [jedisct1/encrypted-dns-server#27]
How can I correctly set up a load balanced dnscrypt server?

I have set up multiple instances of `encrypted-dns`, all sharing the same state file.  However, it appears that the DNS stamp changes upon booting up with the setup.

I'd like to load balance with all of the instances keeping the same DNS stamp and same public IP address.

**Comment by ibksturm** [comment]
look at my git  , i use nginx as loadbalancer https://github.com/ibksturm/dnscrypt-switzerland

**Comment by ibksturm** [comment]
oke, longer version

nginx (with-stream-modul) -> https://github.com/ibksturm/dnscrypt-switzerland/blob/master/etc/nginx/stream.conf.d/dnsc.conf
-> encrypted-01 (statefile encrypted-01.state)
->encrypted-02 (statefile encrypted-02.state)
->encrypted-03 (statefile encrypted-03.state)

every 3 encrypted server belongs to the same secret.key

just of interesstint, how many dns request do you await?
