### ISSUE TITLE
Upstream Server(s)

### ISSUE THREAD

**Issue by dnscrypt-ca** [jedisct1/encrypted-dns-server#3]
The readme currently says:

> The proxy requires a recursive DNS resolver, such as Knot, PowerDNS or Unbound.

Is it expected to remain this way?  I really like the idea of a single self-contained dependency-free executable that provides both DNSCrypt and DoH, but would not want the upstream connection to be provided or even suggested.  I personally like Unbound, but would like the continued freedom to change [or not change] that based on my own evaluation.  Does that make sense?

**Comment by jedisct1** [comment]
Yes, don't worry, it will remain that way.

The only change that can happen is the ability to use multiple upstream servers simultaneously.
