### ISSUE TITLE
How to run this on a Raspberry Pi?

### ISSUE THREAD

**Issue by gspannu** [jedisct1/encrypted-dns-server#31]
I have Unbound configured and running successfully on a Raspberry Pi (4).

Could you provide **some instructions** to deploy Encrypted DNS Server to a Raspberry Pi?

**Comment by jedisct1** [comment]
Hi,

Can you clarify what is missing or unclear in the [instructions](https://github.com/jedisct1/encrypted-dns-server/blob/master/README.md)?
