### ISSUE TITLE
Windows-implementation

### ISSUE THREAD

**Issue by z-ph0ria** [jedisct1/encrypted-dns-server#35]
Is there any windows pre-compiled binaries for this project?
Is it being being developed along-side dnscrypt-proxy?

How do i submit a dnscrypt-server running to resolvers btw?

**Comment by jedisct1** [comment]
Hi!

It should work out of the box on Linux, BSD and MacOS, but some changes would be required for Windows.

The best way to submit a server would be a pull request here: https://github.com/dnscrypt/dnscrypt-resolvers
