### ISSUE TITLE
Provider Name "2.dnscrypt-cert." prefix

### ISSUE THREAD

**Issue by bnkas** [jedisct1/encrypted-dns-server#36]
Hello,

First, I want to say thank you and all the contributors for all these great projects for DNSCrypt. I have been a long time user and now working on launching a couple of servers for the community.

I was able to successfully compile encrypted-dns-server from source and run it as a systemd service. However, I am seeing 2.dnscrypt-cert." prefix is included in my provider name, even though that was not set by me.

In the toml file, I specified my provider name as: **provider_name = "uncloudus.nogoogle.privacydns"**

When the service runs and it echos the provider name, it shows as: **Provider name: 2.dnscrypt-cert.uncloudus.nogoogle.privacydns**. And the stamp generated also shows that the provider name includes "2.dnscrypt-cert." prefix.

*My question is:* how do I remove "2.dnscrypt-cert." prefix from provider name? Is it a default that I can change through encrypted-dns-server settings? Or would I have to use the stamp generator (https://dnscrypt.info/stamps) to generate a new stamp with the provider name I choose?

Thanks

**Comment by jedisct1** [comment]
Hi,

The `2.dnscrypt-cert.` prefix is required by the protocol, as it indicates what protocol version is being used.

But that name is encoded in the stamp and is not something users ever have to type or even see.

In lists, the resolver name is a distinct property. Your server name can totally be `uncloudus.nogoogle.privacydns` or anything even if its provider name is `2.dnscrypt-cert.uncloudus.nogoogle.privacydns`.

**Comment by bnkas** [comment]
Ok. Great. I think I see what you are saying now. Basically, I can use whatever server name I wish in resolver lists, but I have to use the stamp generated by my server as-is and not modify the stamp manually in any way. This make sense now. Thanks.
