### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by military1** [jedisct1/encrypted-dns-server#39]
Hello!
I can’t run it in any way.
Ubuntu 18.04:
`root@dns:~/encrypted-dns-linux-x86_64# sh encrypted-dns
encrypted-dns: 1: encrypted-dns: ELF: not found
encrypted-dns: 4: encrypted-dns: Syntax error: Unterminated quoted string
`
```
root@dns:~/encrypted-dns-linux-x86_64# bash  encrypted-dns
encrypted-dns: encrypted-dns: cannot execute binary file
```

**Comment by jedisct1** [comment]
Precompiled binaries are for `x86_64` architectures.

If you have something else, such as an ARM machine, you need to compile it for your machine.

**Comment by military1** [comment]
```
root@dns:~# uname -m
x86_64
```

**Comment by jedisct1** [comment]
Don't type `bash` before running a command. That would be to run a `bash` script, not a command.

**Comment by military1** [comment]
how to run? from sh?
```
root@dns:~/encrypted-dns-linux-x86_64# sh encrypted-dns
encrypted-dns: 1: encrypted-dns: ELF: not found
encrypted-dns: 4: encrypted-dns: Syntax error: Unterminated quoted string
```

**Comment by jedisct1** [comment]
I'd be more than happy to handle bug reports or anything directly related to this project.

Unfortunately, how to use Linux is a bit off-topic. There are many forums dedicated to Linux, with some even more specialized on Ubuntu, and these are probably a better place to ask for guidance.
