### ISSUE TITLE
Beta Docker image

### ISSUE THREAD

**Issue by lucenera** [jedisct1/encrypted-dns-server#4]
Hi Frank,
about the last bars on issue # 2, I inform you that I have just updated the docker image to the baeeed974b5e beta version.
In fact the dimensions have been reduced considerably, but I still notice oddities in the log. For example, there is a reference to dnscrypt-wrapper.
[docker-log.txt](https://github.com/jedisct1/encrypted-dns-server/files/3653620/docker-log.txt)

**Comment by jedisct1** [comment]
I think you keep reinstalling the other version :)

But the new image looks ready, so I'm going to replace the default one with it soon.

**Comment by lucenera** [comment]
I execute this command: docker pull jedisct1/dnscrypt-server:beta
And in the end I receive confirmation that I have downloaded the latest beta version.

**Comment by lucenera** [comment]
Below I have the screenshot showing that I have the latest version of the container. But now the problem is another: the dnscrypt-wrapper entry no longer appears, but a series of errors and the servers do not work.
![Schermata del 2019-09-25 21-23-02](https://user-images.githubusercontent.com/35407790/65634023-a45f8280-dfdd-11e9-8f8c-ca517e64a425.png)
[docker-log.txt](https://github.com/jedisct1/encrypted-dns-server/files/3654474/docker-log.txt)

**Comment by jedisct1** [comment]
You're still running the old one :)

Instead of 

```sh
docker run --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host \
        jedisct1/dnscrypt-server init -N example.com -E 192.168.1.1:443
```

You should use

```sh
docker run --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host \
        jedisct1/dnscrypt-server:beta init -N example.com -E 192.168.1.1:443
```

**Comment by lucenera** [comment]
I feel stupid.  I understand the mistake, as soon as I am home I try, but surely it goes.

**Comment by jedisct1** [comment]
Docker is complicated, and I'm completely lost with it as well.

**Comment by lucenera** [comment]
Now I find myself in an impasse: how do I get the keys from dnscrypt-wrapper to encrypted-dns? I read in the readme that you can use this command dnscrypt-dns --import-from-dnscrypt-wrapper secret.key
But surely you can use it outside of docker. When counting which file should I copy and where? I have the folder with the keys extracted from the dnscrypt-wrapper container, where do I copy them?...

**Comment by jedisct1** [comment]
Backup the `secret.key` file, this is the most important thing :)

Copy the `secret.key` file (as in [here](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Manually-updating-your-DNSCrypt-server)):

```sh
docker cp secret.key dnscrypt-server-new:/opt/encrypted-dns/etc/keys/secret.key
```

Then do the `init` command:

```sh
export SERVER="<replace with the provider name>"
export SERVER_IP="<replace with your external server IP address without the port>"

docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server:beta init -N $SERVER -E $SERVER_IP:443
```

If everything looks fine, you can the start it:

```sh
docker start dnscrypt-server
```

Maybe I should add an optional parameter to the `init` command that takes a `secret.key` file, that would be easier.

**Comment by lucenera** [comment]
1) I ran the container:
export SERVER="<replace with the provider name>"
export SERVER_IP="<replace with your external server IP address without the port>"

docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server:beta init -N $SERVER -E $SERVER_IP:443

2)I started it and copied the key from the original server (if the container is not active you cannot perform operations on the volume):
docker start dnscrypt-server
docker cp secret.key dnscrypt-server-new:/opt/encrypted-dns/etc/keys/secret.key

3) The result in attached.
![Schermata del 2019-09-26 22-38-48](https://user-images.githubusercontent.com/35407790/65723498-d260c780-e0ae-11e9-9104-9764e2763895.png)

**Comment by jedisct1** [comment]
Try running `docker run --ulimit nofile=90000:90000 --name=dnscrypt-server -p 443:443/udp -p 443:443/tcp --net=host jedisct1/dnscrypt-server:beta init -N $SERVER -E $SERVER_IP:443` again.

**Comment by lucenera** [comment]
If I do it again Docker tells me that the dnscrypt-server name is already used for another container. And if I create one with another name I have to copy the key again and the game starts over again. 
If I delete the old container and restart the command again the same game.

Thu Sep 26 22:46:39 GMT+02:00 2019 Frank Denis <notifications@github.com>:

**Comment by jedisct1** [comment]
I see.

The `secret.key` file is migrated when `init` is called, which works when volumes have been mounted. But if the key is copied after the container runs and not before, we need to also migrate it.

I just pushed a new version. Try the same procedure after a new `docker pull` :)

**Comment by lucenera** [comment]
After a test, the key is imported correctly, because the connection between server and client succeeds.  But anyway I can't solve the queries, that is the IP addresses are not translated.

**Comment by jedisct1** [comment]
Ah! We're getting close :)

I just pushed a new image. Can you give it a try?

**Comment by lucenera** [comment]
The servers are back up with new keys because I changed servers.  Everything works perfectly, but in the end I haven't tried key recovery.  It will be for the next update.
suami 
stamp = 'sdns://AQcAAAAAAAAAETUxLjE1OC4xMDYuNDI6NDQzIPl5tBLA7XTAdkyZG0P642dOwlivYit19hW0I1yxtPMBHDIuZG5zY3J5cHQtY2VydC5pdC5zdWFtaS5jb20'

charis
stamp = 'sdns://AQcAAAAAAAAAETUxLjE1LjEwNi4xNzY6NDQzIEvW6V2Vu6gTWx8Go_PTrPTAjz1-d_Gd9A8KsOPx5NcRGjIuZG5zY3J5cHQtY2VydC5pdC5lZG8uY29t'

**Comment by jedisct1** [comment]
Great!

The stamps for the new servers have been updated, and they work perfectly.

Let me know if you see any regression, but overall, everything should now be faster and more reliable.

**Comment by lucenera** [comment]
Do I always copy the keys folder to back up the keys?
docker cp /opt/encrypted-server/etc/keys ~ and then copy it to the new image?
This time there are no short-term keys.

**Comment by jedisct1** [comment]
Yes! 

The short-term keys are now in the `.state` file. 

In fact, this is the only file you need to copy now.

There is also an easier way, with an exported volume, but I still need to document it :)

**Comment by jedisct1** [comment]
Something cool coming up very soon.

Prometheus metrics. You will be able have fancy graphs to monitor the activity, cache, speed and more.

**Comment by lucenera** [comment]
DNSCrypt is a fantastic protocol and the fact of being decentralized and manageable by anyone is extraordinary. Why isn't it implemented anywhere?
