### ISSUE TITLE
Error Compiling on ARM

### ISSUE THREAD

**Issue by TheBattleWolf** [jedisct1/encrypted-dns-server#41]
During the installation on my PI3 running arch I got the following error:
`error: could not compile 'nix'.`

`Caused by:
  process didn't exit successfully: 'rustc --crate-name nix /home/thebattlewolf/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.16.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C panic=abort -Cembed-bitcode=no -C codegen-units=1 -C metadata=c2fedcef72f83904 -C extra-filename=-c2fedcef72f83904 --out-dir /tmp/cargo-installqCnlHo/release/deps -L dependency=/tmp/cargo-installqCnlHo/release/deps --extern bitflags=/tmp/cargo-installqCnlHo/release/deps/libbitflags-b992c00bea915fd0.rmeta --extern cfg_if=/tmp/cargo-installqCnlHo/release/deps/libcfg_if-803e53fe0a5da7b6.rmeta --extern libc=/tmp/cargo-installqCnlHo/release/deps/liblibc-69d0feabcfd726fc.rmeta --extern void=/tmp/cargo-installqCnlHo/release/deps/libvoid-cd82f05fd1dd77db.rmeta --cap-lints allow' (signal: 9, SIGKILL: kill)`

Could it be that ARM is not supported?
If so will it be in the future?

**Comment by jedisct1** [comment]
Maybe you're running out of memory.  The Rust compiler requires ginormous amounts of memory :(  Try stopping other processes.

But it runs on ARM, I've been running my servers on ARM for a long time.

**Comment by TheBattleWolf** [comment]
I will try that, are there any precompiled versions out there?

**Comment by jedisct1** [comment]
Not for ARM.

**Comment by TheBattleWolf** [comment]
You were spot on, 1GB RAM is not enough, do you know how much would be sufficient?

**Comment by jedisct1** [comment]
I varies across Rust versions, but the best way to get a rough estimate is probably to monitor memory usage of the `rustc` processes during compilation.

**Comment by TheBattleWolf** [comment]
Okay thank you
