### ISSUE TITLE
Metrics endpoint is not exposed when daemonize = true

### ISSUE THREAD

**Issue by felix** [jedisct1/encrypted-dns-server#44]
Simply toggling the config entry `daemonize` to true means the metrics endpoint is no longer exposed.

OS: FreeBSD 12.1
Rust: 1.46.0

**Comment by felix** [comment]
I noticed the commit 0526aba47b5471b31daf36d0265bff2a6f72b382 says that metrics and daemonize are incompatible, what makes this so @jedisct1?

**Comment by jedisct1** [comment]
I have no idea :/

**Comment by felix** [comment]
No worries!
