### ISSUE TITLE
Server stops when daemonize =  false and metrics is enabled

### ISSUE THREAD

**Issue by MeganerdNL** [jedisct1/encrypted-dns-server#48]
I'm running as a systemd service (type=simple)
When I have **daemonize = false** AND **metrics enabled** it still bails out.

According to this commit it shouldn't: 0526aba
No problem in 0.3.19 but a problem in 0.3.20.

`Error: Metrics are incompatible with daemonization - set 'daemonize = false' in the configuration file if you need metrics`

I'm running chrooted

```
[metrics]
type = "prometheus"
listen_addr = "127.0.0.1:9104"
path = "/metrics"
```

**Comment by jedisct1** [comment]
But... yeah... that's exactly what the message says.

You can't enable both :)

**Comment by MeganerdNL** [comment]
But I have **daemonize = false** !
So it is **disabled**, and still this message.

**Comment by jedisct1** [comment]
Oops, I see.

It should be fixed now (updated binaries will be available in a couple minutes).

Thanks for reporting this!

**Comment by MeganerdNL** [comment]
Thanks and you're welcome!
