### ISSUE TITLE
Docker with anonymized server

### ISSUE THREAD

**Issue by lucenera** [jedisct1/encrypted-dns-server#6]
Hi, I updated suami with the new docker image. I added -A to the init. In fact a stamp was created to use suami as a relay. Unfortunately, the server has become unreachable as a DNS server.
![Schermata del 2019-10-15 01-07-59](https://user-images.githubusercontent.com/35407790/66788687-d41cee80-eee8-11e9-81a4-5eb3728898d8.png)

**Comment by jedisct1** [comment]
Aahhhh I broken everything again :(

**Comment by jedisct1** [comment]
Found why.

**Comment by jedisct1** [comment]
New image ready :)

**Comment by lucenera** [comment]
Thank you so much.
