### ISSUE TITLE
undelegated.txt

### ISSUE THREAD

**Issue by black-cerberon** [jedisct1/encrypted-dns-server#63]
Add `id.server` and `hostname.bind` due [RFC4892](https://tools.ietf.org/html/rfc4892).

**Comment by jedisct1** [comment]
Virtually no one operates servers responding to such queries, but why not.

There are variants, such as `authors.bind`, `version.bind` and `version.server`, so we may just want to add `bind` and `server` until they become valid TLDs (very unlikely).
