### ISSUE TITLE
Create More Instructions or a Wiki

### ISSUE THREAD

**Issue by jumpsmm7** [jedisct1/encrypted-dns-server#65]
Okay so I have installed this via rust "option 2" method. Due to the lack of setup instructions, I am at a loss for how to start/stop this as a service.

**Comment by jedisct1** [comment]
https://www.google.com/search?q=how%20to%20run%20something%20as%20a%20service%20on%20linux&ie=utf-8&oe=utf-8#

**Comment by jumpsmm7** [comment]
Thanks for the google crash course. I got it setup through system.d
something like 
**nano /lib/systemd/system/encrypted-dns-server.service**
then
`[Unit]`
`Description=Encrypted Dns Server`
`Documentation=https://github.com/jedisct1/encrypted-dns-server`
`After=network.target`
` `
`[Service]`
`ExecStart=/root/.cargo/bin/encrypted-dns -c /root/.cargo/registry/src/github.com-1285ae84e5963aae/encrypted-dns-0.3.23/encrypted-dns.toml`
`ExecReload=/root/.cargo/bin/encrypted-dns -c /root/.cargo/registry/src/github.com-1285ae84e5963aae/encrypted-dns-0.3.23/encrypted-dns.toml`

`[Install]`
`WantedBy=multi-user.target`

**Comment by pfactum** [comment]
You may also check how it is implemented in the AUR package [here](https://aur.archlinux.org/cgit/aur.git/tree/encrypted-dns.service?h=encrypted-dns).

**Comment by jumpsmm7** [comment]
> 
> 
> You may also check how it is implemented in the AUR package [here](https://aur.archlinux.org/cgit/aur.git/tree/encrypted-dns.service?h=encrypted-dns).

It is nice to see how you do it on arch linux, mine is done on rasbpian.
