### ISSUE TITLE
Unable to generate log file?

### ISSUE THREAD

**Issue by rgzn-aiyun** [jedisct1/encrypted-dns-server#67]
Hi, I didn't see the log file generation during runtime. Is it a configuration error?

**Comment by rgzn-aiyun** [comment]
@jedisct1

**Comment by jedisct1** [comment]
What do you want to log?

**Comment by jedisct1** [comment]
Isn't it something the DNS resolver can  already do? Or even the `tcpdump` command? Or, obliviously, `dnscrypt-proxy`?

I'm not sure that the proxy providing the encryption layer is the right place for that.

**Comment by rgzn-aiyun** [comment]
The log_file setting is invalid?
