### ISSUE TITLE
Anonymized DNS servers

### ISSUE THREAD

**Issue by lucenera** [jedisct1/encrypted-dns-server#7]
These are the suami and charis stamps as relays:
suami -> sdns: // gRE1MS4xNTguMTA2LjQyOjQ0Mw
charis -> sdns: // gRE1MS4xNS4xMDYuMTc2OjQ0Mw

Not if you need to be included in the server file.
Then I have a doubt. Is this syntax correct?
 
routes = [
    {  via=['sdns://gRE1MS4xNS4xMDYuMTc2OjQ0Mw'], via=['sdns://gRE1MS4xNTguMTA2LjQyOjQ0Mw'] }
 ]

How do i check that everything is working? The servers are for sure, but I would like to check as a relay and that the client should go as it should.

**Comment by jedisct1** [comment]
The syntax for the routes is 

```toml
{ server_name = ..., via = [...] }
```

You can try reaching `suami` via `charis`:

```toml
routes = [
  { server_name = 'suami', via = ['sdns://gRE1MS4xNS4xMDYuMTc2OjQ0Mw'] }
]
```

... and `charis` via `suami`:

```toml
routes = [
  { server_name = 'charis', via = ['sdns://gRE1MS4xNTguMTA2LjQyOjQ0Mw'] },
]
```

... and have these two routes, plus (for example) `scaleway-fr` via either suami or charis:

```toml
  { server_name = 'suami', via = ['sdns://gRE1MS4xNS4xMDYuMTc2OjQ0Mw'] },
  { server_name = 'charis', via = ['sdns://gRE1MS4xNTguMTA2LjQyOjQ0Mw'] },
  { server_name = 'scaleway-fr', via = ['sdns://gRE1MS4xNS4xMDYuMTc2OjQ0Mw', 'sdns://gRE1MS4xNTguMTA2LjQyOjQ0Mw'] }
```

**Comment by jedisct1** [comment]
One way to check that it is working is by using `charis` via `suami` and temporarily stopping the relay on `suami`. If you can't resolve anything any more, the relay was definitely used :)

**Comment by jedisct1** [comment]
I just tried your relays and they work perfectly 👍

**Comment by lucenera** [comment]
Thanks. All works fine.

**Comment by jedisct1** [comment]
Relays should probably be in their own list rather than mixed with resolvers.

I'll create it as soon as `dnscrypt-proxy` will actually be able to use such a new list :)

**Comment by lucenera** [comment]
Indeed a public-relay.md
At that point you should only be able to enter the name of the relay and still make everything work as for the servers, automatically choosing the fastest ones. You will have to be able to choose: yes / no relay and whether to use specific relays.

**Comment by jedisct1** [comment]
`public-relay.md` is here now :)

**Comment by lucenera** [comment]
You are the best. Sincerely.
