### ISSUE TITLE
Prometheus

### ISSUE THREAD

**Issue by lucenera** [jedisct1/encrypted-dns-server#8]
I use netdata for the telemetry of the servers in their entirety. But I read about Prometheus. How is it enabled on the servers and how can it be consulted?

**Comment by jedisct1** [comment]
Hi!

The Docker container doesn't have an option to turn this on yet.

But if you look at the `encrypted-dns.toml` file, there is a Prometheus section:

```toml
# [metrics]

# type = "prometheus"
# listen_addr = "0.0.0.0:9100"
# path = "/metrics"
```

Uncommenting all these lines provides an endpoint for Prometheus on port 9100.

Prometheus will regularly fetch data from this endpoint and store it for future queries.

You can make queries directly from the Prometheus UI (such as `rate(client_queries[5m])` to graph the number of queries), or install Grafana that is really cool to build nice dashboards.

**Comment by lucenera** [comment]
It's not directly connected, but what's that folder doing in there (dnscrypt-wrapper)?
Meanwhile I try Grafana.
![Schermata del 2019-10-15 20-47-10](https://user-images.githubusercontent.com/35407790/66860234-1b5cbb00-ef8d-11e9-843e-70e38ea581bb.png)

**Comment by lucenera** [comment]
![Schermata del 2019-10-15 21-31-13](https://user-images.githubusercontent.com/35407790/66863370-261a4e80-ef93-11e9-9de4-4dd752114e10.png)
I'm lost. Could you give me a hand? I created the account on Grafana and I try to set the server to port 9100 as data source. Meanwhile, I removed the comment from the metrics lines in the encrypted-dns.toml file and restarted the container. But I get an error when I check the data source in Grafana. Do I need to set any particular method for authentication to the server? With netdata it seems to me infinitely simpler, but it doesn't give me what I'm looking for, that is info related to queries.

**Comment by lucenera** [comment]
I'll study on it. For the moment, thanks for everything.

**Comment by lucenera** [comment]
I want to tell you that what I wrote had in no way a sarcastic tone and I thank you warmly for what you do, which is exceptional. I understand you can have commitments and I too try to follow your plans between a book of theoretical philosophy, a book of poetic metrics and Dante's Vita Nova.
However I tried to connect with nc and telnet, but I have no reply on that port; telnet tells me connection refused.
I modified the encrypted-dns.toml file using docker's exec uncommenting the part reserved for Prometheus (checked with cat); I restarted the container; i disabled ufw. The result remains that I can't connect to port 9100, which I can do for example on port 9999 with netdata.

**Comment by jedisct1** [comment]
The Docker container has a new option to enable Prometheus :)

**Comment by lucenera** [comment]
I have upgraded my server, how can I activate it?

**Comment by jedisct1** [comment]
It should be accessible from within the container at `http://127.0.0.1:9100/metrics`.

But you probably want it to be accessible outside the container.

This is why the `init` command has a new option: `-M` followed by the IP and port (for example: `-M 0.0.0.0:9100`).

This will make the metrics available at your IP:9100/metrics.

Try accessing this with `nc` or `telnet`. If something responds on that port, you're on the good track! The prometheus server will be able to use it.

**Comment by lucenera** [comment]
I followed all the steps and in fact the encrypted-dns.toml file inside the container is configured as expected (IP: port). But when I try to contact the server on that port, I still get a "failed connection" error. The firewall is disabled both on the server and on the Scaleway platform.
![encrypted-dns toml](https://user-images.githubusercontent.com/35407790/67164847-f8604b80-f37e-11e9-9dab-ee7b3658ab08.png)
![telnet-output-open](https://user-images.githubusercontent.com/35407790/67164849-fbf3d280-f37e-11e9-8c51-73038febf48e.png)

**Comment by lucenera** [comment]
Maybe I understood the banality of the problem by myself, I didn't externalize the door when I gave the "run" to the container. Now I try.

**Comment by jedisct1** [comment]
Docker is complicated :(

Can you try with `0.0.0.0:9100` instead of the external IP?

**Comment by lucenera** [comment]
Perfect, now it works both from telnet and browser. I don't close, I do another couple of tests and I confirm. Meanwhile, thank you very much.

**Comment by lucenera** [comment]
I confirm that everything works perfectly. I don't know how this telemetry works in reality, nor how to use the prometheus data on graphana, but I will study how I can.
One thing that instead relates to encrypted-dns and anonymization: in practice anonymization must be selected as "x" server that passes through the "y", "z", "c", etc. In this way, in order to realize anonymization there will be a need to use those fixed servers as query resolution servers, otherwise some queries will be addressed directly to some servers that do not pass by relay. There should be a way to select the random servers from the public server file (as in the commented "server_name" string and then choose only the relays or even in that case make it automatic and become a simple "true / false " option under "anonymized-dns".
