### ISSUE TITLE
Fails to start when ipv4 and ipv6 use the same port for listen address

### ISSUE THREAD

**Issue by bhanupratapys** [jedisct1/encrypted-dns-server#9]
```
 listen_addrs = [
     { local = "0.0.0.0:1443",    external = "a.a.a.a:1443" },
     { local = "[::]:1443",       external = "[bb:bb::1]:1443" }
 ]
```
I tried starting the program with above code, it always stops with ``[ERROR] Unable to listen to the requested IPs and ports: [[::]:1443/TCP: Address already in use (os error 98)]``.

It works perfectly fine when I change the port values for either one of ipv4/ipv6 address.

**Comment by IceCodeNew** [comment]
Run `ss -nlp 'sport = :1443'` as root and reply with the command output please.

**Comment by bhanupratapys** [comment]
> Run `ss -nlp 'sport = :1443'` as root and reply with the command output please.

There is nothing running on the above mentioned port. I don't think this issue is related to some other program running on that port.

**Comment by jedisct1** [comment]
It's a Linux specific behavior where listening to an IPv6 wildcard socket also listens to IPv4.

It should be fixed now.
